export enum DisplayEnum {
  BANNER_CONTAINER = 1,
  ICON_CONTAINER = 2,
  NAV_HOME_CONTAINER = 3,
  SLIDE_POST_CONTAINER = 4,
  SLIDE_PARTNER_CONTAINER = 5,
  BANNER_LEFT_CONTAINER = 6,
  BANNER_RIGHT_CONTAINER = 7,
  BANNER_MERGE_CONTAINER = 8,
  LEADER_SLIDE_CONTAINER = 9,

  NEWS_1_CONTAINER = 10,
  NEWS_2_CONTAINER = 11,
  NEWS_3_CONTAINER = 12,
  NEWS_4_CONTAINER = 13,

  PRODUCTS_SLIDE_CONTAINER = 20,
  SERVICE_SLIDE_CONTAINER = 21,
  PRODUCT_DETAIL_CONTAINER = 22,

  RECRUIMENT_SLIDE_CONTAINER = 30,
  RECRUIMENT_SLIDE_2_CONTAINER = 32,
  RECRUIMENT_FORM_CONTAINER = 33,

  CAPACITY_QLCL_CONTAINER = 40,
  CAPACITY_ALL_TEXT_CONTAINER = 41,

  HEADERBUTTON = 50,
  BANNER_MAIN_CONTAINER = 49,
  BANNER_RECRUITMENT_CONTAINER = 48,
  POST_HIGHLIGHT_CONTAINER = 47,
}
